site_name: wb-learn-notes
site_url: https://mydomain.org/site
theme:
  name: readthedocs
docs_dir: docs
site_dir: site

nav:
  - Home: index.md
#  - Guides: 
#    - MkDocs: guides/mkdocs.md
#    - others: guides/others.md
#  - book-notes:
#      - book: book-notes/index.md
#  - tool-notes: 
#    - tool: tool-notes/index.md
#  - work-notes:
#    - work: work-notes/index.md
#  - language:
#    - cpp: 
#      - cpp: language/cpp/index.md
#    - language: language/index.md
#  - platform-system:
#    - platform-system: platform-system/index.md